import { ArtworkData } from "./artworkData";

// Mock data for artworks

export const artworkData: ArtworkData[] = [
  // Artworks by John Doe
  {
    id: "1",
    title: "Sunset Overdrive",
    artist: "John Doe",
    image: "https://via.placeholder.com/150",
    hashtags: ["sunset", "nature", "art"],
    description: "A beautiful sunset painting.",
    coordinates: { latitude: 40.73061, longitude: -73.935242 },
    userID: "1",
    uploadDate: "2024-10-01",
  },
  {
    id: "2",
    title: "Urban Exploration",
    artist: "John Doe",
    image: "https://via.placeholder.com/150",
    hashtags: ["city", "exploration", "urban"],
    description: "Exploring the depths of the city.",
    coordinates: { latitude: 34.052235, longitude: -118.243683 },
    userID: "1",
    uploadDate: "2024-10-02",
  },
  {
    id: "3",
    title: "Calm Waters",
    artist: "John Doe",
    image: "https://via.placeholder.com/150",
    hashtags: ["lake", "calm", "water"],
    description: "A serene view of a lake at dawn.",
    coordinates: { latitude: 36.169941, longitude: -115.139832 },
    userID: "1",
    uploadDate: "2024-10-03",
  },
  {
    id: "4",
    title: "Mountain Peaks",
    artist: "John Doe",
    image: "https://via.placeholder.com/150",
    hashtags: ["mountain", "peaks", "nature"],
    description: "High above the mountains.",
    coordinates: { latitude: 39.739236, longitude: -104.990251 },
    userID: "1",
    uploadDate: "2024-10-04",
  },
  {
    id: "5",
    title: "Forest Path",
    artist: "John Doe",
    image: "https://via.placeholder.com/150",
    hashtags: ["forest", "path", "nature"],
    description: "A path through the forest.",
    coordinates: { latitude: 47.606209, longitude: -122.332069 },
    userID: "1",
    uploadDate: "2024-10-05",
  },

  // Artworks by Jane Smith
  {
    id: "6",
    title: "Mountain Breeze",
    artist: "Jane Smith",
    image: "https://via.placeholder.com/150",
    hashtags: ["mountains", "breeze", "scenery"],
    description: "Capturing the cool mountain breeze.",
    coordinates: { latitude: 40.73061, longitude: -73.935242 },
    userID: "2",
    uploadDate: "2024-10-06",
  },
  {
    id: "7",
    title: "City Nights",
    artist: "Jane Smith",
    image: "https://via.placeholder.com/150",
    hashtags: ["city", "nights", "lights"],
    description: "The city illuminated at night.",
    coordinates: { latitude: 34.052235, longitude: -118.243683 },
    userID: "2",
    uploadDate: "2024-10-01",
  },
  {
    id: "8",
    title: "The Ocean",
    artist: "Jane Smith",
    image: "https://via.placeholder.com/150",
    hashtags: ["ocean", "waves", "beach"],
    description: "Waves crashing on the shore.",
    coordinates: { latitude: 36.169941, longitude: -115.139832 },
    userID: "2",
    uploadDate: "2024-10-22",
  },
  {
    id: "9",
    title: "Snowy Mountains",
    artist: "Jane Smith",
    image: "https://via.placeholder.com/150",
    hashtags: ["snow", "mountains", "winter"],
    description: "Snow-covered mountains.",
    coordinates: { latitude: 39.739236, longitude: -104.990251 },
    userID: "2",
    uploadDate: "2024-10-20",
  },
  {
    id: "10",
    title: "River Stream",
    artist: "Jane Smith",
    image: "https://via.placeholder.com/150",
    hashtags: ["river", "stream", "nature"],
    description: "A calm river stream.",
    coordinates: { latitude: 47.606209, longitude: -122.332069 },
    userID: "2",
    uploadDate: "2024-10-12",
  },

  // Artworks by Alice Johnson
  {
    id: "11",
    title: "Desert Sunset",
    artist: "Alice Johnson",
    image: "https://via.placeholder.com/150",
    hashtags: ["desert", "sunset", "landscape"],
    description: "The sun setting over the desert.",
    coordinates: { latitude: 35.46756, longitude: -97.516428 },
    userID: "3",
    uploadDate: "2024-10-28",
  },
  {
    id: "12",
    title: "City Skyline",
    artist: "Alice Johnson",
    image: "https://via.placeholder.com/150",
    hashtags: ["skyline", "city", "urban"],
    description: "The skyline of a bustling city.",
    coordinates: { latitude: 29.760427, longitude: -95.369804 },
    userID: "3",
    uploadDate: "2024-10-15",
  },
  {
    id: "13",
    title: "Frozen Lake",
    artist: "Alice Johnson",
    image: "https://via.placeholder.com/150",
    hashtags: ["lake", "frozen", "winter"],
    description: "A lake frozen over in winter.",
    coordinates: { latitude: 41.878114, longitude: -87.629798 },
    userID: "3",
    uploadDate: "2024-10-11",
  },
  {
    id: "14",
    title: "Spring Blossoms",
    artist: "Alice Johnson",
    image: "https://via.placeholder.com/150",
    hashtags: ["spring", "blossoms", "flowers"],
    description: "Flowers blooming in spring.",
    coordinates: { latitude: 33.448376, longitude: -112.074036 },
    userID: "3",
    uploadDate: "2024-10-17",
  },
  {
    id: "15",
    title: "Misty Forest",
    artist: "Alice Johnson",
    image: "https://via.placeholder.com/150",
    hashtags: ["mist", "forest", "trees"],
    description: "A forest shrouded in mist.",
    coordinates: { latitude: 32.776664, longitude: -96.796988 },
    userID: "3",
    uploadDate: "2024-10-05",
  },

  // Artworks by Michael Brown
  {
    id: "16",
    title: "Rocky Cliffs",
    artist: "Michael Brown",
    image: "https://via.placeholder.com/150",
    hashtags: ["rocks", "cliffs", "ocean"],
    description: "Steep cliffs by the ocean.",
    coordinates: { latitude: 25.76168, longitude: -80.19179 },
    userID: "4",
    uploadDate: "2024-10-02",
  },
  {
    id: "17",
    title: "Golden Gate",
    artist: "Michael Brown",
    image: "https://via.placeholder.com/150",
    hashtags: ["bridge", "golden", "landmark"],
    description: "Golden Gate Bridge on a clear day.",
    coordinates: { latitude: 37.774929, longitude: -122.419416 },
    userID: "4",
    uploadDate: "2024-10-09",
  },
  {
    id: "18",
    title: "Deep Forest",
    artist: "Michael Brown",
    image: "https://via.placeholder.com/150",
    hashtags: ["forest", "deep", "nature"],
    description: "Lost in the heart of the forest.",
    coordinates: { latitude: 34.052235, longitude: -118.243683 },
    userID: "4",
    uploadDate: "2024-10-20",
  },
  {
    id: "19",
    title: "Sandy Dunes",
    artist: "Michael Brown",
    image: "https://via.placeholder.com/150",
    hashtags: ["desert", "dunes", "sand"],
    description: "Rolling dunes in the desert.",
    coordinates: { latitude: 36.778259, longitude: -119.417931 },
    userID: "4",
    uploadDate: "2024-10-07",
  },
  {
    id: "20",
    title: "Lighthouse",
    artist: "Michael Brown",
    image: "https://via.placeholder.com/150",
    hashtags: ["lighthouse", "coast", "sea"],
    description: "A lighthouse on a rocky coast.",
    coordinates: { latitude: 40.712776, longitude: -74.005974 },
    userID: "4",
    uploadDate: "2024-10-04",
  },

  // Artworks by Sarah Lee
  {
    id: "21",
    title: "Golden Fields",
    artist: "Sarah Lee",
    image: "https://via.placeholder.com/150",
    hashtags: ["fields", "golden", "landscape"],
    description: "Golden fields at sunset.",
    coordinates: { latitude: 37.774929, longitude: -122.419416 },
    userID: "5",
    uploadDate: "2024-10-04",
  },
  {
    id: "22",
    title: "City Rush",
    artist: "Sarah Lee",
    image: "https://via.placeholder.com/150",
    hashtags: ["city", "rush", "urban"],
    description: "The rush of a busy city.",
    coordinates: { latitude: 34.052235, longitude: -118.243683 },
    userID: "5",
    uploadDate: "2024-10-01",
  },
  {
    id: "23",
    title: "Autumn Leaves",
    artist: "Sarah Lee",
    image: "https://via.placeholder.com/150",
    hashtags: ["autumn", "leaves", "fall"],
    description: "Beautiful autumn leaves.",
    coordinates: { latitude: 40.712776, longitude: -74.005974 },
    userID: "5",
    uploadDate: "2024-10-21",
  },
  {
    id: "24",
    title: "Mountain Fog",
    artist: "Sarah Lee",
    image: "https://via.placeholder.com/150",
    hashtags: ["mountain", "fog", "nature"],
    description: "Foggy mountain landscape.",
    coordinates: { latitude: 41.878114, longitude: -87.629798 },
    userID: "5",
    uploadDate: "2024-10-26",
  },
  {
    id: "25",
    title: "Crystal Waters",
    artist: "Sarah Lee",
    image: "https://via.placeholder.com/150",
    hashtags: ["water", "clear", "river"],
    description: "Crystal clear river water.",
    coordinates: { latitude: 47.606209, longitude: -122.332069 },
    userID: "5",
    uploadDate: "2024-10-14",
  },
];
